title: Jacob Westergren # your name (or website title) here
logo: "/images/temp_profile_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Fifth-year Computer Science student at KTH, pursuing a Master's in Machine Learning. 
  <br><br>
  Deep Learning Enthusiast, specialized in visual and audial data. 
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-westergren">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Custom CSS for circular profile picture
custom_css: |
  .profile-pic img {
    width: 150px; /* Adjust size as needed */
    height: 150px; /* Adjust size as needed */
    border-radius: 50%; /* Makes the image circular */
    object-fit: cover; /* Ensures the image covers the circular area */
  }
